### ISSUE TITLE
bug in 

### ISSUE THREAD

**Issue by iBelow** [vbobroff-app/FluentWpfChromes#3]
if i adding new window (Modal dialog) with
 ```
<fluentWpfChromes:AcrylicChrome.AcrylicChrome>
        <fluentWpfChromes:AcrylicChrome/>
    </fluentWpfChromes:AcrylicChrome.AcrylicChrome>
``` 
this code, after closing a window - all app is freezing
and i cant activate owner window 
tested on .Net 4.8

**Comment by vbobroff-app** [comment]
Hi! 
Try to change AllowStartUpFrozen property.
